services:
  app:
    build:
      context: container
      args:
        - REQUIREMENTS=requirements.txt
    volumes:
      - ./container/app:/app
    ports:
      - "8081:8081"
    environment:
      - DEBUG=False
      - PORT=8081
      - PYTHONPATH=/app/objector/
    command: gunicorn -w 4 objector.wsgi
