version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=unsafe-secret-key
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SOCIAL_AUTH_AUTH0_DOMAIN=${SOCIAL_AUTH_AUTH0_DOMAIN}
      - SOCIAL_AUTH_AUTH0_KEY=${SOCIAL_AUTH_AUTH0_KEY}
      - SOCIAL_AUTH_AUTH0_SECRET=${SOCIAL_AUTH_AUTH0_SECRET}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_SUBJECT_PREFIX=${EMAIL_SUBJECT_PREFIX}
    depends_on:
      - db
