version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=unsafe-secret-key
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
      - SOCIAL_AUTH_AUTH0_DOMAIN=${SOCIAL_AUTH_AUTH0_DOMAIN}
      - SOCIAL_AUTH_AUTH0_KEY=${SOCIAL_AUTH_AUTH0_KEY}
      - SOCIAL_AUTH_AUTH0_SECRET=${SOCIAL_AUTH_AUTH0_SECRET}
    depends_on:
      - db
