services:
  app:
    build: container
    volumes:
      - ./container/app:/app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - SECRET_KEY="unsafe-secret-key"
      - DEBUG=True
    command: python objector/manage.py runserver 0.0.0.0:8000
