services:
  app:
    build:
      context: objector-container
      args:
        - REQUIREMENTS=requirements.dev.txt
    volumes:
      - ./objector-container/app:/app
    ports:
      - "8081:8081"
    environment:
      - DEBUG=True
      - SECRET_KEY="unsafe-secret-key"
    command: python objector/manage.py runserver 0.0.0.0:8081
