services:
  app:
    build: container
    volumes:
      - ./container/app:/app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - SECRET_KEY="unsafe-secret-key"
      - DEBUG=True
      - SOCIAL_AUTH_AUTH0_DOMAIN=${SOCIAL_AUTH_AUTH0_DOMAIN}
      - SOCIAL_AUTH_AUTH0_KEY=${SOCIAL_AUTH_AUTH0_KEY}
      - SOCIAL_AUTH_AUTH0_SECRET=${SOCIAL_AUTH_AUTH0_SECRET}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    command: python objector/manage.py runserver 0.0.0.0:8000