services:
  app:
    build:
      context: container
    volumes:
      - ./container/app:/app
    ports:
      - "8081:8081"
    environment:
      - SECRET_KEY="unsafe-secret-key"
      - DEBUG=True
    command: python objector/manage.py runserver 0.0.0.0:8081
